### ISSUE TITLE
OSError: Failed to interpret file './data_process/int_1_len_24_91_up/TRAIN_X_1.npy' as a pickle

### ISSUE THREAD

**Issue by Nicolas-zhaos** [Ch4ndelier/LSTM_Zero_Velocity_classification#1]
Thanks for your code. After i download the processed datasets and run the train_lstm.py , i encounter with this Error **OSError: Failed to interpret file './data_process/int_1_len_24_91_up/TRAIN_X_1.npy' as a pickle**,what should i do to reslove it.

**Comment by Ch4ndelier** [comment]
I guess it's the path problem, you may try the absolute path or if you use Windows you should change '/' to '\'.
I don't know for sure but you can give it a try. I believe it's not some kind of syntax problems or func misuse.

**Comment by Ch4ndelier** [comment]
> Thanks for your code. After i download the processed datasets and run the train_lstm.py , i encounter with this Error **OSError: Failed to interpret file './data_process/int_1_len_24_91_up/TRAIN_X_1.npy' as a pickle**,what should i do to reslove it.

I guess it's the path problem, you may try the absolute path or if you use Windows you should change '/' to ''.
I don't know for sure but you can give it a try. I believe it's not some kind of syntax problems or func misuse.

**Comment by Nicolas-zhaos** [comment]
After carefully checking, i found that the reson is the datasets are not fully download.I download it again and the program works well.
